#include <stdio.h>

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

int main()
{
        int a = 1;
        int b = 1;

        int sum = 0;

        int c = 0;

        while(c < 4000000)
        {
                c = a + b;
                a = b;
                b = c;

                if(c % 2 == 0) {
                        sum = sum + c;
                }
        }

        printf("The sum of even fibonacci numbers up to 1M is: %d\n", sum);
}
