#include <stdio.h>

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

int main()
{
        int a = 1;
        int b = 1;

        int sum = 0;

        int c = 0;

        // While the fibonacci term does not exceed four million
        while(c < 4000000)
        {
                // Sum the previous two values
                c = a + b;
                
                // Set current values as previous values
                a = b;
                b = c;

                // Check whether the fibonnaci term has an even parity
                if(c % 2 == 0) {
                        // If even party is Fact, add fibonacci term to the sum.
                        sum = sum + c;
                }
        }

        printf("%d\n", sum);
}
