/*

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

*/

public class Problem12 {
    public static void main(String[] args) {
        int triangles = 0;
        int count;

        // For each natural number up to forever
        for(int i = 1; ; i++) {
            // Get the next triangle number
            triangles = triangles + i;
            count = 0;

            // Let's test it against all possible divisors below the square root
            // of the triangle number itself.
            for(int j = 1; j <= Math.sqrt(triangles); j++) {
                if(triangles % j == 0) {
                    // If the triangle number passes the test to find it's
                    // divisor j you find two divisors, it takes two to tango
                    // and two numbers to multiply.
                    count = count + 2;
                }
            }

            // Break up the party if you find over fivehundred divisors.
            if(count > 500 ) {
                System.out.println(triangles);
                break;
            }
        }
    }
}
